# Generated by Django 5.2.7 on 2025-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField()),
                ('q2A', models.TextField(blank=True, null=True)),
                ('q2B', models.TextField(blank=True, null=True)),
                ('q2C', models.TextField(blank=True, null=True)),
                ('q3', models.TextField(blank=True, null=True)),
                ('q4A', models.TextField(blank=True, null=True)),
                ('q4B', models.TextField(blank=True, null=True)),
                ('q4C', models.TextField(blank=True, null=True)),
                ('q4D', models.TextField(blank=True, null=True)),
                ('q4E', models.TextField(blank=True, null=True)),
                ('q4F', models.TextField(blank=True, null=True)),
                ('q4G', models.TextField(blank=True, null=True)),
                ('q5A', models.TextField(blank=True, null=True)),
                ('q5B', models.TextField(blank=True, null=True)),
                ('q5C', models.TextField(blank=True, null=True)),
                ('q6', models.TextField(blank=True, null=True)),
                ('qE1', models.TextField(blank=True, null=True)),
                ('qE2', models.TextField(blank=True, null=True)),
                ('qE3', models.TextField(blank=True, null=True)),
                ('qE4', models.TextField(blank=True, null=True)),
                ('qE5', models.TextField(blank=True, null=True)),
                ('qE6', models.TextField(blank=True, null=True)),
                ('qE7', models.TextField(blank=True, null=True)),
                ('qE8', models.TextField(blank=True, null=True)),
                ('qE9', models.TextField(blank=True, null=True)),
                ('qE10', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='api_institu_created_3b935a_idx')],
            },
        ),
    ]
